# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service



service: hello-world

provider:
  name: aws
  runtime: nodejs6.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource:
        - { "Fn::GetAtt": ["NamesDynamoDBTable", "Arn" ] }
  environment:
    NAMES_TABLE: { "Ref": "NamesDynamoDBTable" }

functions:
  saveName:
    handler: handler.saveName
    events:
      - http:
          path: name
          method: post
          cors: true
  getName:
    handler: handler.getName
    events:
      - http:
          path: name
          method: get
          cors: true

resources:
  Resources:
    NamesDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: name
            AttributeType: S
        KeySchema:
          -
            AttributeName: name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
